begin;
select plan(13);
set local role anon;
select lives_ok($$ select public.request_invite('  NEW@example.test  ') $$, 'anonymous visitors can request an invite');
select lives_ok($$ select public.request_invite('new@example.test') $$, 'repeated requests are idempotent');
select throws_ok($$ select public.request_invite('invalid') $$, '22023', 'Enter a valid email address.', 'invalid email is rejected');
select throws_ok($$ select public.request_invite(null) $$, '22023', 'Enter a valid email address.', 'null email is rejected');
select throws_ok($$ select * from public.invites $$, '42501', 'permission denied for table invites', 'anonymous visitors cannot read invite records');
select throws_ok($$ update public.invites set expires_at = null $$, '42501', 'permission denied for table invites', 'anonymous visitors cannot mutate invite records directly');
reset role;
select is((select count(*)::integer from public.invites where email = 'new@example.test'), 1, 'email normalization prevents duplicate invitations');
select ok((select expires_at > now() and expires_at <= now() + interval '24 hours' from public.invites where email = 'new@example.test'), 'self-service eligibility expires in 24 hours');
select is(public.hook_allow_invited_user('{"user":{"email":"new@example.test"}}'), '{}'::jsonb, 'requested email passes signup hook');
update public.invites set expires_at = now() - interval '1 second' where email = 'new@example.test';
set local role anon;
select public.request_invite('new@example.test');
reset role;
select ok((select expires_at > now() from public.invites where email = 'new@example.test'), 'expired eligibility can be renewed');
insert into auth.users (id, email) values ('00000000-0000-0000-0000-000000000099', 'new@example.test');
select is((select claimed_by from public.invites where email = 'new@example.test'), '00000000-0000-0000-0000-000000000099'::uuid, 'signup claims the invite');
set local role anon;
select public.request_invite('new@example.test');
reset role;
select is((select claimed_by from public.invites where email = 'new@example.test'), '00000000-0000-0000-0000-000000000099'::uuid, 'requesting again never reopens a claimed invite');
select is((select visibility::text from public.profiles where user_id = '00000000-0000-0000-0000-000000000099'), 'private', 'new profile is private');
select * from finish();
rollback;
